---
- name: Create temp directory to store the template
  command: mktemp -d /tmp/openshift-log-writer-ansible-XXXXXX
  register: mktemp
  changed_when: False

- set_fact:
    tempdir: "{{ mktemp.stdout }}"

- name: "create project for {{ olw_namespace }}"
  command: "oc adm new-project {{ olw_namespace }}"
  ignore_errors: true

- name: create "{{ olw_sa }}" serviceaccount
  oc_serviceaccount:
    name: "{{ olw_sa }}"
    namespace: "{{ olw_namespace }}"

- name: set service account permissions
  command: "oc adm policy {{ item.r_kind }} {{ item.r_name }} system:serviceaccount:{{ olw_namespace }}:{{ olw_sa }}"
  run_once: true
  ignore_errors: true
  with_items:
  - r_kind: add-cluster-role-to-user
    r_name: cluster-reader

  # running as command until oc_secret supports config file image secrets
- name: "Create image pull secret"
  command: "oc secrets new dockercfgjson .dockerconfigjson=/var/lib/origin/.docker/config.json -n {{ olw_namespace }}"
  run_once: true
  ignore_errors: true

- name: copy pod writer template
  copy:
    src: log-writer.yml
    dest: "{{ tempdir }}/log-writer.yml"

- name: Set pod writer template
  oc_obj:
    kind: template
    name: log-writer
    namespace: "{{ olw_namespace }}" 
    state: present
    files: "{{ tempdir }}/log-writer.yml"
    debug: true
    force: true
    delete_after: true
  ignore_errors: true

- debug:
    msg: "{{ olw_namespace }}"

- name: "Create bc,is,dc for apps in {{ opl_namespace }} from template"
  shell: "oc process oso-log-writer -n {{ olw_namespace }} | oc create -n {{ olw_namespace }} -f -"
  run_once: true
  ignore_errors: true

- name: "join with pod-logger project network"
  command: "oc adm pod-network join-projects --to=openshift-pod-logger {{ olw_namespace }}"
  run_once: true
  ignore_errors: true

- name: Delete temp directory
  file:
    name: "{{ tempdir }}"
    state: absent
