---
- hosts: localhost
  gather_facts: no
  vars_files:
  - /root/default_vars.yml

  vars:
    scanning_cron:
    - name: cron_scan_pods
      minute: "15"
      hour: 13
      job: "/usr/local/bin/cron-scan-pods.sh &>/dev/null"

    - name: inmem_scan
      minute: "15"
      hour: "5,13,21"
      job: "/usr/local/bin/cron-in-memory-scan.sh &>/dev/null"

  tasks:
  - name: "Create custom scan report directory for image-inspector"
    file:
      path: "{{ item.ii_name }}"
      state: "{{ item.ii_state}}"
      recurse: "{{ item.ii_recurse }}"
      mode: 0755
    with_items:
    - ii_name: /var/log/clam
      ii_state: directory
      ii_recurse: yes
    - ii_name: /etc/openshift_tools
      ii_state: directory
      ii_recurse: yes
    - ii_name: /etc/origin/node
      ii_state: directory
      ii_recurse: yes
      ii_recurse: no
    - ii_name: /etc/sysconfig/docker 
      ii_state: touch
      ii_recurse: no
    - ii_name: /usr/bin/docker-current 
      ii_state: touch
      ii_recurse: no
    - ii_name: /var/run/docker.sock 
      ii_state: touch
      ii_recurse: no
    - ii_name: /etc/origin/node/node-config.yaml
      ii_state: touch
      ii_recurse: no

  # Running as commands because mount module doesn't mount properly on some clusters
  - name: "Ensure directories are correctly mounted for in memory scanning"
    command: "{{ item }}"
    with_items:
    - "mount --bind -o ro /host/etc/origin/node/node-config.yaml /etc/origin/node/node-config.yaml"
    - "mount --bind -o ro /host/var/run/docker.sock /var/run/docker.sock"
    - "mount --bind -o ro /host/usr/bin/docker-current /usr/bin/docker-current"
    - "mount --bind -o ro /host/etc/sysconfig/docker /etc/sysconfig/docker"

  - name: Setup Cron
    cron:
      name: "{{ item.name }}"
      job: "{{ item.job }}"
      minute: "{{ item.minute | default('*', True) }}"
      hour: "{{ item.hour | default('*', True) }}"
      day: "{{ item.day | default('*', True) }}"
      month: "{{ item.month | default('*', True) }}"
      weekday: "{{ item.weekday | default('*', True) }}"
    with_items:
    - "{{ scanning_cron }}"
