# /usr/local/bin/start.sh will start the service

{% if base_os == "rhel7" %}
FROM openshifttools/oso-rhel7-ops-base:latest
{% elif base_os == "centos7" %}
FROM openshifttools/oso-centos7-ops-base:latest
{% endif %}

# Pause indefinitely if asked to do so.
ARG OO_PAUSE_ON_BUILD
RUN test "$OO_PAUSE_ON_BUILD" = "true" && while sleep 10; do true; done || :

ADD scripts/ /usr/local/bin/

ADD root/ /root/

# Install clam server utilities and signature updater
RUN yum install -y clamav-server \
                   clamav-scanner \
                   clamav-unofficial-sigs \
                   openshift-tools-scripts-clam-update \
                   python2-pip \
                   python2-boto3 \
                   python2-botocore && \
    yum clean all

RUN mkdir -p /host/usr/bin /logs /var/log/journal

ADD clamd/ /etc/clamd.d/

USER 0

# Start processes
CMD /usr/local/bin/start.sh
