---
- hosts: localhost
  gather_facts: no
  vars_files:
  - /root/default_vars.yml

  vars:
    scanning_cron:
    - name: cron_scan_images
      minute: 1
      hour: 1
      day: 1
      job: "/usr/local/bin/duplicate_accounts_report.sh &>/dev/null"

  tasks:
  - name: Setup Cron
    cron:
      name: "{{ item.name }}"
      job: "{{ item.job }}"
      minute: "{{ item.minute | default('*', True) }}"
      hour: "{{ item.hour | default('*', True) }}"
      day: "{{ item.day | default('*', True) }}"
      month: "{{ item.month | default('*', True) }}"
      weekday: "{{ item.weekday | default('*', True) }}"
    with_items:
    - "{{ scanning_cron }}"
