---
apiVersion: v1
kind: Template
metadata:
  name: oso-clam-scanner
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      template: oso-clam-scanner
    name: "oso-${PLAT}-ops-base"
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: "oso-${PLAT}-ops-base:latest"
    postCommit: {}
    resources: {}
    source:
      contextDir: "docker/oso-ops-base/${PLAT}"
      git:
        ref: oso-clam-scanner
        uri: https://github.com/rhdedgar/openshift-tools
      secrets: []
      type: Git
    strategy:
      dockerStrategy:
        env:
        - name: OO_PAUSE_ON_BUILD
          value: "false"
        from:
          kind: ImageStreamTag
          name: "${PLAT}:latest"
      type: Docker
    triggers:
    - imageChange: {}
      type: ImageChange
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      template: oso-clam-scanner
    name: oso-clam-scanner
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: "oso-${PLAT}-clam-scanner:latest"
    postCommit: {}
    resources: {}
    source:
      contextDir: "docker/oso-clam-scanner/${PLAT}"
      git:
        ref: oso-clam-scanner
        uri: https://github.com/rhdedgar/openshift-tools
      secrets: []
      type: Git
    strategy:
      dockerStrategy:
        env:
        - name: OO_PAUSE_ON_BUILD
          value: "false"
        from:
          kind: ImageStreamTag
          name: "oso-${PLAT}-ops-base:latest"
      type: Docker
    triggers:
    - imageChange: {}
      type: ImageChange
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      template: oso-clam-scanner
    name: "${PLAT}"
  spec:
    dockerImageRepository: "library/${PLAT}"
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: "registry.access.redhat.com/${PLAT}:latest"
      importPolicy: {}
      name: latest
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      template: oso-clam-scanner
    name: "oso-${PLAT}-ops-base"
  spec:
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: "library/oso-${PLAT}-ops-base:latest"
      importPolicy: {}
      name: latest
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      template: oso-clam-scanner
    name: "oso-${PLAT}-clam-scanner"
  spec:
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: "library/oso-${PLAT}-clam-scanner:latest"
      importPolicy: {}
      name: latest
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      template: oso-clam-scanner
    name: oso-clam-scanner
  spec:
    replicas: 1
    selector:
      deploymentconfig: oso-clam-scanner
    strategy:
      resources: {}
      type: Rolling
    template:
      metadata:
        labels:
          deploymentconfig: oso-clam-scanner
      spec:
        containers:
        - env:
          - name: OO_PAUSE_ON_START
            value: "false"
          image: "oso-clam-scanner/oso-${PLAT}-clam-scanner:latest"
          imagePullPolicy: Always
          name: oso-clam-scanner
          resources: {}
          securityContext:
            runAsUser: 0
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /host
            name: oso-clam-scanner-host-filesystem
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        serviceAccount: clamscan
        serviceAccountName: clamscan
        terminationGracePeriodSeconds: 30
        volumes:
        - name: oso-clam-scanner-host-filesystem
          hostPath:
            path: /
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - oso-clam-scanner
        from:
          kind: ImageStreamTag
          name: "oso-${PLAT}-clam-scanner:latest"
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      template: oso-clam-scanner
    name: clam-scanner
  spec:
    selector:
      deploymentconfig: oso-clam-scanner
    sessionAffinity: None
    type: ClusterIP
parameters:
- description: Platform name
  name: PLAT
  value: rhel7
