---
- hosts: localhost
  gather_facts: no
  vars_files:
  - /root/default_vars.yml

  vars:
    sigpull_cron:
    - name: cron_pull_signatures
      minute: "15"
      hour: "*/12"
      job: "/usr/local/bin/pull_clam_signatures &>/dev/null"

  tasks:
  - name: "Create mount points for CREs"
    file:
      path: "{{ item.ii_name }}"
      state: "{{ item.ii_state}}"
      recurse: "{{ item.ii_recurse }}"
      mode: 0755
    with_items:
    - ii_name: /etc/sysconfig/docker 
      ii_state: touch
      ii_recurse: no
    - ii_name: /usr/bin/docker-current 
      ii_state: touch
      ii_recurse: no
    - ii_name: /var/run/docker.sock 
      ii_state: touch
      ii_recurse: no
    - ii_name: /var/run/crio
      ii_state: directory
      ii_recurse: yes
    - ii_name: /var/run/crio/crio.sock 
      ii_state: touch
      ii_recurse: no
    - ii_name: /etc/sysconfig/crio-storage
      ii_state: touch
      ii_recurse: no
    - ii_name: /etc/sysconfig/crio-network
      ii_state: touch
      ii_recurse: no
    ignore_errors: true

  - name: "Ensure directories are correctly mounted"
    command: "{{ item }}"
    with_items:
    - "mount --bind -o ro /host/var/run/docker.sock /var/run/docker.sock"
    - "mount --bind -o ro /host/var/run/crio/crio.sock /var/run/crio/crio.sock"
    - "mount --bind -o ro /host/usr/bin/docker-current /usr/bin/docker-current"
    - "mount --bind -o ro /host/etc/sysconfig/docker /etc/sysconfig/docker"
    ignore_errors: true

  - name: "Ensure the clamd pid and socket directory has been created"
    file:
      path: "{{ item.csname }}"
      state: "{{ item.csstate}}"
      recurse: "{{ item.csrecurse }}"
      mode: 0755
      owner: clamscan
      group: clamscan
    with_items:
    - csname: /var/run/clamd.scan 
      csstate: directory
      csrecurse: yes

  - name: Remove default clam update cron jobs
    file:
      path: "{{ item.cron_name }}"
      state: "{{ item.cron_state }}"
    with_items:
    - cron_name: /etc/cron.d/clamav-update
      cron_state: absent
    - cron_name: /etc/cron.d/clamav-unofficial-sigs
      cron_state: absent

  - name: Setup Cron
    cron:
      name: "{{ item.name }}"
      job: "{{ item.job }}"
      minute: "{{ item.minute | default('*', True) }}"
      hour: "{{ item.hour | default('*', True) }}"
      day: "{{ item.day | default('*', True) }}"
      month: "{{ item.month | default('*', True) }}"
      weekday: "{{ item.weekday | default('*', True) }}"
    with_items:
    - "{{ sigpull_cron }}"
