---
apiVersion: v1 
kind: Template
metadata:
  creationTimestamp: null
  generation: 1
  labels:
    provider: openshift
    clam-controller-host: "true"
  name: oso-clam-controller 
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      template: oso-clam-controller
    name: "oso-${PLAT}-ops-base"
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: "oso-${PLAT}-ops-base:latest"
    postCommit: {}
    resources: {}
    source:
      contextDir: "docker/oso-ops-base/${PLAT}"
      git:
        ref: oso-image-inspector
        uri: https://github.com/rhdedgar/openshift-tools
      secrets: []
      type: Git
    strategy:
      dockerStrategy:
        env:
        - name: OO_PAUSE_ON_BUILD
          value: "false"
        from:
          kind: ImageStreamTag
          name: "${PLAT}:latest"
        noCache: true
      type: Docker
    triggers:
    - imageChange: {}
      type: ImageChange
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      template: oso-clam-controller
    name: oso-clam-controller
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: "oso-${PLAT}-clam-controller:latest"
    postCommit: {}
    resources: {}
    source:
      contextDir: "docker/oso-clam-controller/${PLAT}"
      git:
        ref: oso-image-inspector
        uri: https://github.com/rhdedgar/openshift-tools
      secrets: []
      type: Git
    strategy:
      dockerStrategy:
        env:
        - name: OO_PAUSE_ON_BUILD
          value: "false"
        from:
          kind: ImageStreamTag
          name: "oso-${PLAT}-ops-base:latest"
      type: Docker
    triggers:
    - imageChange: {}
      type: ImageChange
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      template: oso-clam-controller
    name: "${PLAT}"
  spec:
    dockerImageRepository: "library/${PLAT}"
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: "registry.access.redhat.com/${PLAT}:latest"
      importPolicy: {}
      name: latest
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      template: oso-clam-controller
    name: "oso-${PLAT}-ops-base"
  spec:
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: "library/oso-${PLAT}-ops-base:latest"
      importPolicy: {}
      name: latest
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      template: oso-clam-controller
    name: "oso-${PLAT}-clam-controller"
  spec:
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: "library/oso-${PLAT}-clam-controller:latest"
      importPolicy: {}
      name: latest
- kind: Service
  apiVersion: v1
  metadata:
    name: oso-clam-controller
    annotations:
      description: service for openshift-clam-controller
  spec:
    ports:
    - name: web
      port: 8080
      targetPort: 8080
    selector:
      name: oso-clam-controller
- apiVersion: extensions/v1beta1
  kind: DaemonSet
  metadata:
    labels:
      template: oso-clam-controller
    name: oso-clam-controller
  selector:
    matchLabels:
      name: oso-clam-controller
  spec:
    strategy:
      resources: {}
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        name: oso-clam-controller
        labels:
          name: oso-clam-controller
      spec:
        containers:
        - env:
          - name: OO_PAUSE_ON_START
            value: "false"
          image: "${NAMESPACE}/oso-${PLAT}-clam-controller:latest"
          imagePullPolicy: Always
          noCache: true
          name: oso-clam-controller 
          resources: {}
          securityContext:
            privileged: true
            runAsUser: 0
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /host
            name: oso-clam-controller-host-filesystem
          - mountPath: /secrets
            name: oso-clam-controller-secrets
        dnsPolicy: ClusterFirst
        nodeSelector:
          clam-controller-enabled: "True"
        restartPolicy: Always
        securityContext: {}
        serviceAccount: clamcontroller
        serviceAccountName: clamcontroller
        terminationGracePeriodSeconds: 30
        volumes:
        - name: oso-clam-controller-host-filesystem
          hostPath:
            path: /
        - name: oso-clam-controller-secrets
          secret:
            secretName: oso-clam-controller-secrets
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - oso-clam-controller
        from:
          kind: ImageStreamTag
          name: "oso-${PLAT}-clam-controller:latest"
      type: ImageChange
parameters:
- description: Platform name
  name: PLAT
  value: rhel7
- description: Project name
  name: NAMESPACE
  value: openshift-clam-controller
