---
- hosts: localhost
  gather_facts: no
  vars_files:
  - /root/default_vars.yml
  - /host/etc/openshift_tools/monitoring-config.yml

  vars:
    scanning_cron:
    - name: cron_scan_images
      minute: 1
      hour: 1
      day: 1
      month: 3
      job: "/usr/local/bin/scan_images &>/dev/null"

  tasks:
  - name: "Create custom scan report directory for image-inspector"
    file:
      path: "{{ item.ii_name }}"
      state: "{{ item.ii_state}}"
      recurse: "{{ item.ii_recurse }}"
      mode: 0755
    with_items:
    - ii_name: /var/log/clam
      ii_state: directory
      ii_recurse: yes
    - ii_name: /etc/openshift_tools
      ii_state: directory
      ii_recurse: yes
    - ii_name: /etc/origin/node
      ii_state: directory
      ii_recurse: yes
    - ii_name: /etc/openshift_tools/scanreport_config.yml
      ii_state: touch
      ii_recurse: no
    - ii_name: /etc/origin/node/node-config.yaml
      ii_state: touch
      ii_recurse: no

  - name: populate templated config file
    copy:
      content: |
        node_hostname: {{ metric_sender_config['host']['name'] }}
        cluster_name: {{ oso_cluster_id }}
      dest: /etc/openshift_tools/scanreport_config.yml

  - name: Setup Cron
    cron:
      name: "{{ item.name }}"
      job: "{{ item.job }}"
      minute: "{{ item.minute | default('*', True) }}"
      hour: "{{ item.hour | default('*', True) }}"
      day: "{{ item.day | default('*', True) }}"
      month: "{{ item.month | default('*', True) }}"
      weekday: "{{ item.weekday | default('*', True) }}"
    with_items:
    - "{{ scanning_cron }}"
