---
- hosts: localhost
  gather_facts: no
  vars_files:
  - /root/default_vars.yml
  - /host/etc/origin/node/node-config.yaml

  vars:
    scanning_cron:
    - name: cron_scan_pods
      minute: "15"
      hour: 13
      job: "/usr/local/bin/cron-scan-pods.sh &>/dev/null"

#    - name: inmem_scan
#      minute: "15"
#      hour: "13"
#      job: "/usr/local/bin/cron-in-memory-scan.sh &>/dev/null"

#    - name: upload_scanlogs
#      minute: "15"
#      hour: "14"
#      job: "/usr/local/bin/upload_scanlogs &>/dev/null"

  tasks:
  - name: "Create custom scan report directory for image-inspector"
    file:
      path: "{{ item.ii_name }}"
      state: "{{ item.ii_state}}"
      recurse: "{{ item.ii_recurse }}"
      mode: 0755
    with_items:
    - ii_name: /var/log/clam
      ii_state: directory
      ii_recurse: yes
    - ii_name: /etc/openshift_tools
      ii_state: directory
      ii_recurse: yes
    - ii_name: /etc/openshift_tools/scanreport_config.yml
      ii_state: touch
      ii_recurse: no
    - ii_name: /etc/sysconfig/docker 
      ii_state: touch
      ii_recurse: no
    - ii_name: /usr/bin/docker-current 
      ii_state: touch
      ii_recurse: no
    - ii_name: /var/run/docker.sock 
      ii_state: touch
      ii_recurse: no

  - name: Make node name accessible
    set_fact:
      temp_name: "{{ kubeletArguments['node-labels'] }}"

  - name: populate templated config file
    copy:
      content: |
        node_hostname: {{ temp_name[4].split('=')[1] }}
        cluster_name: {{ temp_name[4].split('=')[1].split('-node')[0] }}
      dest: /etc/openshift_tools/scanreport_config.yml

#  - name: "Bind mounts for scanning"
#    mount:
#      opts: "{{ item.mnt_opts }}"
#      fstype: auto
#      state: mounted
#      name: "{{ item.mnt_name }}"
#      src: "{{ item.mnt_src }}"
#    with_items:
#    - mnt_src: "/host/etc/sysconfig/docker"
#      mnt_name: "/etc/sysconfig/docker"
#      mnt_opts: "bind,ro"
#    - mnt_src:  "/host/usr/bin/docker-current"
#      mnt_name: "/usr/bin/docker-current"
#      mnt_opts: "bind,ro"
#    - mnt_src: "/host/var/run/docker.sock"
#      mnt_name: "/var/run/docker.sock"
#      mnt_opts: "bind,ro"

  - name: Setup Cron
    cron:
      name: "{{ item.name }}"
      job: "{{ item.job }}"
      minute: "{{ item.minute | default('*', True) }}"
      hour: "{{ item.hour | default('*', True) }}"
      day: "{{ item.day | default('*', True) }}"
      month: "{{ item.month | default('*', True) }}"
      weekday: "{{ item.weekday | default('*', True) }}"
    with_items:
    - "{{ scanning_cron }}"
