---
- name: copy advanced config file into place
  copy:
    src: files/adv-audit.yaml
    dest: "{{ omac_auditConfig_policyFile }}"
    mode: 755
  when: omac_auditConfig_policyFile is defined

- name: "auditConfig.enabled"
  yedit:
    src: /etc/origin/master/master-config.yaml
    key: auditConfig.enabled
    value: "{{ omac_auditConfig_enabled }}"
  notify: restart openshift master services

- name: "deploy master audit config options"
  yedit:
    src: /etc/origin/master/master-config.yaml
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    state: "{{ 'present' if item.value != '' else 'absent' }}"
  notify: restart openshift master services
  with_items:
  - key: auditConfig.auditFilePath
    value: "{{ omac_auditConfig_auditFilePath | default('') }}"
  - key: auditConfig.maximumFileRetentionDays
    value: "{{ omac_auditConfig_maximumFileRetentionDays | default('') }}"
  - key: auditConfig.maximumRetainedFiles
    value: "{{ omac_auditConfig_maximumRetainedFiles | default('') }}"
  - key: auditConfig.maximumFileSizeMegabytes
    value: "{{ omac_auditConfig_maximumFileSizeMegabytes | default('') }}"
  - key: auditConfig.policyFile
    value: "{{ omac_auditConfig_policyFile | default('') }}"
  - key: auditConfig.logFormat
    value: "{{ omac_auditConfig_logFormat | default('') }}"
